# Generated by Django 3.2.3 on 2021-07-19 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('price', models.IntegerField(db_column='Price')),
                ('description', models.TextField(db_column='Description', max_length=25)),
                ('image', models.ImageField(db_column='Image', upload_to='static/Images')),
                ('long_description', models.TextField(db_column='Long Description')),
            ],
        ),
        migrations.CreateModel(
            name='carts',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecartApp.products')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('status', models.BooleanField(db_column='Status')),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
