# Generated by Django 3.2.3 on 2021-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('price', models.IntegerField(db_column='Price')),
                ('description', models.TextField(db_column='Description', max_length=25)),
                ('image', models.ImageField(db_column='Image', upload_to='static/Images')),
            ],
        ),
    ]
