# Generated by Django 3.2.5 on 2021-07-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(db_column='Image', upload_to=''),
        ),
    ]
