# Generated by Django 3.2.3 on 2021-07-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productss',
            new_name='products',
        ),
    ]
