# Generated by Django 3.2.3 on 2021-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0002_rename_productss_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='long_description',
            field=models.TextField(db_column='Long Description', default='No long product description'),
            preserve_default=False,
        ),
    ]
