# Generated by Django 3.2.3 on 2021-07-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0003_products_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_column='User', max_length=100)),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('product_id', models.ForeignKey(db_column='Product_Id', on_delete=django.db.models.deletion.DO_NOTHING, to='ecartApp.products')),
            ],
        ),
    ]
