# Generated by Django 3.2.3 on 2021-07-12 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecartApp', '0004_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.BooleanField(db_column='Status'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
