# Generated by Django 3.2.3 on 2021-07-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0005_auto_20210712_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='product_id',
            field=models.ForeignKey(db_column='Product_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecartApp.products'),
        ),
    ]
