# Generated by Django 3.2.3 on 2021-07-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0006_auto_20210713_0012'),
    ]
