# Generated by Django 3.2.3 on 2021-07-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecartApp', '0007_auto_20210713_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carts',
        ),
    ]
